### ISSUE TITLE
Replace MessageModifier with target model construction API

### ISSUE THREAD

**Issue by petringo** [fmidev/aviation-message-archiver#12]
Replace `fi.fmi.avi.archiver.message.modifier.MessageModifier` interface with new interface to populate the archive message model builder. This new interface should contain one `void` method with two parameters:

1. source immutable parsing result object (from #9) and

2. target archive model builder object (`AviationMessage.Builder`).

Rename any classes when appropriate. E.g. consider renaming `fi.fmi.avi.archiver.message.AviationMessage` to `ArchiveAviationMessage` or something alike.

Refactor any existing modifier to satisfy new API.

**Comment by kasarit** [comment]
Not sure about the naming. Should MessageModifier be called something else?

**Comment by petringo** [comment]
I thought the same, but haven't yet figured any appropriate name describing the nature of this component (populating target archival message model from parsed input data, and possibly doing validation).
